### ISSUE TITLE
Syntax error in webb.py for Python 3+

### ISSUE THREAD

**Issue by Talha-Ahmed-1** [hardikvasa/webb#13]
In webb.py 
`print url` exists *print* without parenthesis is not supported in Python 3+.
It should be `print (url)`

**Comment by moutaigua8183** [comment]
I have the same issue.

```
Traceback (most recent call last):
  File "13_rpi_web_crawl.py", line 1, in <module>
    from webb import webb
  File "D:\Miniconda3\envs\test\lib\site-packages\webb\webb.py", line 213
    print url
```

After looking into webb.py,  actually you can fix it by adding the bracket around "url" at line 213
```
# from
print url  
# to
print (url)
```
My guess is that the author missed this one while transitioning to Python 3.

**Comment by sherdwhite** [comment]
Guessing this lib is abandoned?

**Comment by richlysakowski** [comment]
> I have the same issue.
> 
> ```
> Traceback (most recent call last):
>   File "13_rpi_web_crawl.py", line 1, in <module>
>     from webb import webb
>   File "D:\Miniconda3\envs\test\lib\site-packages\webb\webb.py", line 213
>     print url
> ```
> 
> After looking into webb.py, actually you can fix it by adding the bracket around "url" at line 213
> 
> ```
> # from
> print url  
> # to
> print (url)
> ```
> 
> My guess is that the author missed this one while transitioning to Python 3.

The fix entails using parentheses, e.g., ```print("text to print to stdout")```, not brackets []
