### ISSUE TITLE
Missing print parentheses – crashes in Python 3

### ISSUE THREAD

**Issue by akaihola** [hardikvasa/webb#6]
```
$ pip install webb
Collecting webb
  Downloading webb-0.9.2.5.zip
Building wheels for collected packages: webb
  Running setup.py bdist_wheel for webb ... done
  Stored in directory: ~/.cache/pip/wheels/7d/0a/f6/18b2ead5525698dde6ccd20469ea588c93d6ff5736f6a25c0f
Successfully built webb
Installing collected packages: webb
Successfully installed webb-0.9.2.5

$ python
Python 3.5.0 (default, Oct  5 2015, 11:46:01) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from webb import webb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib64/python3.5/site-packages/webb/webb.py", line 213
    print url  
            ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by hardikvasa** [comment]
thank you! the file has been updated!
